events { worker_connections 1024; }

http {
    upstream backend_servers {
        server dummy-app:5000;
    }

    server {
        listen 80;
        
        # THIS IS THE INTENTIONAL TYPO
        server_name localhost; 
        
        location / {
            proxy_pass http://backend_servers;
        }
    }
}